{% set name = "qlient-core" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qlient-core-{{ version }}.tar.gz
  sha256: 71efc3a71d95630408838d23dc1ef7f3560a4afc5322594dabf606f333056616

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - importlib-metadata >=4.11.4,<5.0.0

test:
  imports:
    - qlient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://qlient-org.github.io/python-qlient-core/site/
  summary: The core for a blazingly fast and modern graphql client designed with simplicity in mind.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
